/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from types/types.d.ts:
/** @const */
var types$types = {};
/**
 * @record
 * @struct
 */
types$types.thisIsAmbient = function() {};
/** @type {*} */
types$types.thisIsAmbient.prototype.good;
/**
 * @record
 * @struct
 */
types$types.thisIsNot = function() {};
/** @type {*} */
types$types.thisIsNot.prototype.bad;

/**
 * @param {!types$types.thisIsAmbient} a
 * @return {*}
 */
types$types.usingAmbientParamTypeInOwnModule = function(a) {};

/**
 * @param {!types$types.thisIsNot} a
 * @return {*}
 */
types$types.usingNonAmbientParamTypeInOwnModule = function(a) {};
// externs from importing_types.d.ts:
/** @const */
var importing_types = {};

/**
 * @param {!types$types.thisIsAmbient} a
 * @return {*}
 */
importing_types.usingAmbientParamTypeInAnotherModule = function(a) {};

/**
 * @param {!types.types.thisIsNot} a
 * @return {*}
 */
importing_types.usingNonAmbientParamTypeInAnotherModule = function(a) {};
